# Generated by Django 5.2.1 on 2026-08-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('learning', '0002_material_source_endpoint_material_source_record_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_url', models.URLField()),
                ('seed_video_id', models.CharField(max_length=32)),
                ('seed_title', models.CharField(max_length=500)),
                ('research_query', models.CharField(max_length=500)),
                ('requested_video_count', models.PositiveSmallIntegerField(default=10)),
                ('topic_model', models.CharField(default='lda', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_runs', to='learning.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_runs', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_runs', to='learning.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('keywords', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('radius', models.FloatField(default=28)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='ingestion.researchrun')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ResearchVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('channel_title', models.CharField(blank=True, max_length=255)),
                ('published_at', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=32)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('transcript_status', models.CharField(default='missing', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_videos', to='learning.material')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ingestion.researchrun')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ResearchVideoTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.researchtheme')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.researchvideo')),
            ],
            options={
                'unique_together': {('video', 'theme')},
            },
        ),
        migrations.AddField(
            model_name='researchvideo',
            name='themes',
            field=models.ManyToManyField(related_name='videos', through='ingestion.ResearchVideoTheme', to='ingestion.researchtheme'),
        ),
        migrations.CreateModel(
            name='ContentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_backend', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_chunks', to='learning.material')),
                ('research_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_chunks', to='ingestion.researchvideo')),
            ],
            options={
                'ordering': ['material_id', 'ordinal'],
                'unique_together': {('material', 'ordinal')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='researchvideo',
            unique_together={('run', 'youtube_id')},
        ),
    ]
