# Generated by Django 5.2.1 on 2026-08-03 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
        ('chatbot', '0002_chatmessage_metadata'),
        ('learning', '0006_quizquestion_is_reviewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_model_suggested', models.BooleanField(default=False)),
                ('model_backend', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_themes', to='learning.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_question_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course__code', 'label'],
            },
        ),
        migrations.CreateModel(
            name='AnalyzedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('relevance_score', models.FloatField(default=1.0)),
                ('relevance_backend', models.CharField(default='rules', max_length=40)),
                ('classification_reason', models.CharField(blank=True, max_length=255)),
                ('suggested_theme_label', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzed_questions', to='learning.course')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_analysis', to='chatbot.chatmessage')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='analytics_app.questiontheme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='questiontheme',
            constraint=models.UniqueConstraint(fields=('course', 'label'), name='unique_question_theme_per_course'),
        ),
    ]
