# Generated by Django 5.2.1 on 2026-08-14 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0003_analyticsevent_tracking_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('purpose', models.TextField(help_text='Explain exactly why this information is being collected and how it will be used.')),
                ('consent_text', models.TextField(default='I voluntarily consent to this information being used for aggregated learning-access analytics. I understand that I may decline or later withdraw my response without affecting access to learning content.')),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('is_active', models.BooleanField(default=False, help_text='Only a reviewed questionnaire can be shown to users.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_analytics_questionnaires', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_analytics_questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable reporting key, for example gender or province.', max_length=80)),
                ('label', models.CharField(max_length=220)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('question_type', models.CharField(choices=[('gender', 'Gender (optional demographic)'), ('region', 'Region (coarse geography)'), ('select', 'Single choice'), ('multiselect', 'Multiple choice'), ('text', 'Short text')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='A JSON list of allowed choices for select questions.')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='analytics_app.analyticsquestionnaire')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('questionnaire', 'key'), name='unique_analytics_question_key')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsQuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('consent_given', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField()),
                ('consent_version', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='analytics_app.analyticsquestionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_questionnaire_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('questionnaire', 'user'), name='one_analytics_response_per_user')],
            },
        ),
    ]
