# Generated by Django 6.0.5 on 2026-07-29 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('text', 'Short Text')], default='text', max_length=10)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_option', models.CharField(blank=True, max_length=255)),
                ('expected_keywords', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='BaselineAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['course__code', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.baselineassessment')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('selected_option', models.CharField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.assessmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.assessmentquestion')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.baselineassessment'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lecturers', models.ManyToManyField(blank=True, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='courses_enrolled', to=settings.AUTH_USER_MODEL)),
                ('teaching_assistants', models.ManyToManyField(blank=True, related_name='courses_supported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_assessments', to='learning.course'),
        ),
        migrations.CreateModel(
            name='LecturerPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prompt_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_prompts', to='learning.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course__code', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.course')),
            ],
            options={
                'ordering': ['course__code', 'title'],
                'unique_together': {('course', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('source_origin', models.CharField(choices=[('internal', 'Internal Upload'), ('external', 'External Source')], default='internal', max_length=20)),
                ('source_type', models.CharField(choices=[('file', 'Uploaded File'), ('website', 'Website'), ('video', 'Video'), ('paper', 'Academic Paper'), ('other', 'Other')], default='file', max_length=20)),
                ('source_provider', models.CharField(blank=True, help_text='Examples: Uploaded by Lecturer, OpenAlex, Semantic Scholar, YouTube.', max_length=120)),
                ('file', models.FileField(blank=True, upload_to='materials/')),
                ('external_url', models.URLField(blank=True)),
                ('original_source_url', models.URLField(blank=True)),
                ('youtube_title', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags.', max_length=255)),
                ('source_citation', models.TextField(blank=True)),
                ('semantic_text', models.TextField(blank=True)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learning.course')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='learning.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='learning.topic'),
        ),
    ]
