# Generated by Django 6.0.5 on 2026-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='source_endpoint',
            field=models.CharField(blank=True, help_text='Exact upstream endpoint or ingest route used to create this material.', max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='source_record_id',
            field=models.CharField(blank=True, help_text='Upstream record identifier such as DOI, OpenAlex ID, Springer identifier, or video ID.', max_length=255),
        ),
    ]
