# Generated by Django 5.2.1 on 2026-08-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_material_source_endpoint_material_source_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='source_preview_url',
            field=models.CharField(blank=True, help_text='Direct PDF or same-origin preview URL supplied by the source provider.', max_length=1000),
        ),
    ]
