# Generated by Django 5.2.1 on 2026-08-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_material_source_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='authors',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='material',
            name='doi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='isbn',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='material',
            name='journal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='volume_issue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='source_type',
            field=models.CharField(choices=[('file', 'Uploaded File'), ('website', 'Website'), ('video', 'Video'), ('paper', 'Academic Paper'), ('journal', 'Journal Article'), ('book', 'Book'), ('blog', 'Blog Post'), ('other', 'Other')], default='file', max_length=20),
        ),
    ]
