# Generated by Django 5.2.1 on 2026-08-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_quiz_quizattempt_quizquestion_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
